In [ ]:
#algebra linear -> x + 2 = 5 -> x = 3 (resolver sistemas de equações lineares)

#x + y = 10 -----> (0,10), (2,8), (-3,13) ... infin sol (diofantina)
#2x - y == 11

x = 2 \
x+y = 10

$$  \alpha + \beta = 10$$

In [3]:
import numpy as np
import scipy as sc
import sympy as sy

In [8]:
#escalar, vetor e matriz
#escalar = numero (tensor de ordem 0)
x = 2 #escalar
x2 = np.array([1,2,3]) #vetor com 3 elementos scalares
x3 = np.array([[1],[2],[3]]) #matriz com 3 elementos vetores com elementos  escalares
x4 = np.array([[1,2,3],[2,3,1],[3,1,2]]) #matriz tradicional    

In [9]:
print(x4)

[[1 2 3]
 [2 3 1]
 [3 1 2]]


In [10]:
import pandas as pd

In [14]:
lista = [1,2,3,4,5]
df = pd.DataFrame({'coluna1': lista})

In [15]:
df

coluna1
0        1
1        2
2        3
3        4
4        5

In [16]:
type(df)

pandas.core.frame.DataFrame